services:
  postgres_db:
    container_name: vibe-link-postgres-db
    image: postgres:15.0-alpine
    env_file:
      - env/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis_db:
    container_name: vibe-link-redis_db
    image: redis:alpine
    env_file:
      - env/redis.env
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  backend:
    container_name: vibe-link-backend
    build: .
    env_file:
      - env/backend.env
    stdin_open: true
    tty: true
    depends_on:
      - postgres_db
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  celery_worker:
    container_name: vibe-link-celery-worker
    build: .
    env_file:
      - env/backend.env
    stdin_open: true
    tty: true
    depends_on:
      - postgres_db
      - redis_db
    volumes:
      - .:/app/
    command: celery -A core.celery.app worker -l INFO

  celery_beat:
    container_name: vibe-link-celery-beat
    build: .
    env_file:
      - env/backend.env
    stdin_open: true
    tty: true
    depends_on:
      - postgres_db
      - redis_db
    volumes:
      - .:/app/
    command: celery -A core.celery.app beat -l INFO

  flower:
    container_name: vibe-link-flower
    build: .
    env_file:
      - env/backend.env
    stdin_open: true
    tty: true
    depends_on:
      - postgres_db
      - redis_db
    volumes:
      - .:/app/
    ports:
      - "5555:5555"
    command: celery -A core.celery.app flower -l INFO

volumes:
  postgres-data:
  redis-data:
